### ISSUE TITLE
Python 3.12 Support Release

### ISSUE THREAD

**Issue by cyschneck** [ajdawson/eofs#145]
There is a pip install issue when attempting to download eofs on Python 3.12

```
$ pip install eofs
Collecting eofs
  Using cached eofs-1.4.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/setup.py", line 38, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```
It seems to be the result of the transition from versioneer to setuptools_scm. It seems that this will be solved when [pyproject.toml](https://github.com/ajdawson/eofs/blob/main/pyproject.toml) is released

Is there a timeline for when this will be released?

**Comment by ajdawson** [comment]
I have made a new release today 1.4.1, does that solve this problem?

**Comment by cyschneck** [comment]
Thanks you!
